config/routes.rb
Rails.application.routes.draw do
  root 'actives#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'help' => 'pages#help', as: 'help'
  get 'videos' => 'pages#videos', as: 'videos'
  get 'numerical_character' => 'pages#numerical_character', as: 'numerical'

  resources :actives
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obraztsov_DiplomWork</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %>
  <%= javascript_importmap_tags %>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="application.css">

  <% facebook_link = "https://www.facebook.com/profile.php?id=100010499292910" %>
  <% youtube_link = "https://www.youtube.com/channel/UCMZ-pfxg39-4EwAfyB2_LCQ" %>
</head>

<body>
<div class="head-box">
  <div class="d-flex flex-column flex-md-row align-items-center">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="10" height="32" class="me-2" viewBox="0 0 118 94" role="img">
        <title>Active matter</title>

        <div style="display: flex; margin-top: 10px; margin-left: 0px;">
          <%= image_tag 'logo.png', alt: 'logo', style: 'width: 100px; height: 100px; border-radius: 50%;' %>
        </div>
      </svg>
      <span class="fs-4 font-weight-bold" style="color: white; margin-left: 20px;"><b>Brushbots matter</b></span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">

    <span class="me-3 py-2 text-dark text-decoration-none">
      <% unless @current_page == home_path %>
        <%= link_to "Головна сторінка", home_path, :class => "my-button green-button", target: "_self" %></span>
      <% end %>
      <span class="me-3 py-2 text-dark text-decoration-none">
      <% unless @current_page == numerical_path %>
        <%= link_to "Числові характеристики", numerical_path, id: "numerical-button", :class => "my-button orange-button", target: "_self" %></span>
      <% end %>
      <span class="me-3 py-2 text-dark text-decoration-none">
      <% unless @current_page == videos_path %>
        <%= link_to "Відеоматеріали", videos_path, id: "videos-button", :class => "my-button blue-button", target: "_self" %></span>
      <% end %>
      <span class="me-3 py-2 text-dark text-decoration-none">
      <% unless @current_page == about_path %>
        <%= link_to "Про нас", about_path, id: "about-button", :class => "my-button yellow-button", target: "_self" %></span>
      <% end %>
      <span class="me-3 py-2 text-dark text-decoration-none">
      <% unless @current_page == help_path %>
        <%= link_to "Потрібна допомога?", help_path, id: "help-button", :class => "my-button white-button", target: "_self" %></span>
       <% end %>
      </nav>
  </div>

  <!--  <script>
        document.getElementById("numerical-button").addEventListener("click", function() {
            location.reload();
        });
        document.getElementById("videos-button").addEventListener("click", function() {
            location.reload();
        });
        document.getElementById("about-button").addEventListener("click", function() {
            location.reload();
        });
        document.getElementById("help-button").addEventListener("click", function() {
            location.reload();
        });
    </script>-->

  <%= yield %>
  <footer>
    <div class="section">
      <h3>Про нас</h3>
      <p style="text-align: justify">Програмне забезпечення було розроблено Образцовим Дмитром — студентом 4 курсу факультету комп’ютерних
        наук
        ХНУ імені В. Н. Каразіна.</p>
      <p style="text-align: justify">Детальнішу інформацію можна дізнатися на відповідній сторінці «Про нас».</p>
    </div>
    <div class="section">
      <h3>Послуги</h3>
      <ul>
        <li>Активна матерія</li>
        <li>Дослідження різних систем активної матерії</li>
        <li>Розгорнуті результати аналізу досліджень</li>
      </ul>
    </div>
    <div class="section">
      <h3>Зв'язатися з нами</h3>
      <ul>
        <li>
          <%= image_tag 'gmail.png', :class => "rounded-image", style: 'margin-right: 5px' %>
          <a style="display: inline-flex; align-items: center;">xa12850498@student.karazin.ua</a>
        </li>
        <li>
          <%= image_tag 'phone_icon.png', :class => "rounded-image", style: 'margin-right: 5px' %>
          <a style="display: inline-flex; align-items: center;">(+380) 66-122-0753</a>
        </li>
      </ul>
    </div>
    <div class="section">
      <h3>Соціальні мережі</h3>
      <ul>
        <li>
          <%= image_tag 'facebook.png', alt: 'Book one input data', width: 20, height: 20, style: 'margin-right: 5px' %>
          <a href="<%= facebook_link %>" style="display: inline-flex; align-items: center;">Facebook</a>
        </li>
        <li>
          <%= image_tag 'youtube.png', alt: 'Book one input data', width: 20, height: 20, style: 'margin-right: 5px' %>
          <a href="<%= youtube_link %>" style="display: inline-flex; align-items: center;">YouTube</a>
        </li>
      </ul>
    </div>
  </footer>
</div>
</body>
</html>
<!-- new_post_path из результата rails routes-->
<!-- span - ссылки -->
<!-- home_path - home выставляется в routes -->